### ISSUE TITLE
One line, two buttons

### ISSUE THREAD

**Issue by adan-ea** [sethcottle/littlelink#124]
Hi there, 
Love the project, have been using it for a while now. 
Could you help me find a way to create two buttons on one line? 
I have two youtube channels (the main one and the VOD) that i would like to merge into one button. I tried stuff but got only so far
![image](https://github.com/sethcottle/littlelink/assets/57812567/88c5ead6-8435-4ed9-ac87-4847adc2d49e)

The reason i'm asking is because other people might like this feature too (I hope)!

Tell me if you want the little code i got on this :]

**Comment by sethcottle** [comment]
Hey @adan-ea! Thanks for the kind note, let's see what I can do to help you out with this. On a side note, this is probably a good push for me to revamp how buttons work anyway, they're super rudimentary and use fixed PX widths as of right now which can be a little wonky. But basing all of this on today's code, here's what you can do!

Find your way over to `brands.css` since this is where we house the button CSS for branded buttons! You'll find this:

```css
/* Buttons
–––––––––––––––––––––––––––––––––––––––––––––––––– */

.button,
button {
  display: inline-block;
  text-decoration: none;
  height: 100%;
  text-align: center;
  vertical-align: middle;
  font-size: 18px;
  width: 300px;
  font-weight: 700;
  line-height: 20px;
  padding: 14px 12px 12px 12px;
  letter-spacing: 0.1px;
  white-space: wrap;
  outline: none;
  border-radius: 8px;
  cursor: pointer;
}     
button:hover,
.button:focus {
  color: #212121;
  border-color: #888;
  outline: #7AB8FF solid 3px
}
.button.button-primary {
  color: #fff;
  filter: brightness(90%);
}
.button.button-primary:hover,
.button.button-primary:focus {
  color: #fff;
  filter: brightness(90%);
}
```

I'm going to drop the following to the bottom of it:

```css
.button.button-small {
  width: 134px;
}
```

This will make it so the button inherits all the other styling. Here's what the CSS looks like with that snippet added in...

```css
/* Buttons
–––––––––––––––––––––––––––––––––––––––––––––––––– */

.button,
button {
  display: inline-block;
  text-decoration: none;
  height: 100%;
  text-align: center;
  vertical-align: middle;
  font-size: 18px;
  width: 300px;
  font-weight: 700;
  line-height: 20px;
  padding: 14px 12px 12px 12px;
  letter-spacing: 0.1px;
  white-space: wrap;
  outline: none;
  border-radius: 8px;
  cursor: pointer;
}     
button:hover,
.button:focus {
  color: #212121;
  border-color: #888;
  outline: #7AB8FF solid 3px
}
.button.button-primary {
  color: #fff;
  filter: brightness(90%);
}
.button.button-primary:hover,
.button.button-primary:focus {
  color: #fff;
  filter: brightness(90%);
}
.button.button-small {
  width: 134px;
}
```

That'll get them aligned with the current fixed button width. Now get back over to `index.html` and this is what we'll use for the `<a>`.

```html
<!-- Side by Side YouTube Buttons -->
<a class="button button-small button-yt" href="#" target="_blank" rel="noopener" role="button"><img class="icon" aria-hidden="true" src="images/icons/youtube.svg" alt="YouTube Logo">Main</a>
<a class="button button-small button-yt" href="#" target="_blank" rel="noopener" role="button"><img class="icon" aria-hidden="true" src="images/icons/youtube.svg" alt="YouTube Logo">VOD</a>
<br>
 ```

 Hopefully this gives you the same result I got, which looked like this:
  
![CleanShot 2024-07-08 at 13 48 26@2x](https://github.com/sethcottle/littlelink/assets/1301949/ea9b01f6-c0a3-4c3d-8b05-1ccae8473f5e)

Let me know if you run into any issues with this!
